spring.datasource.url=jdbc:postgresql://localhost:5432/ai_saas_db
spring.datasource.username=saas_user
spring.datasource.password=saas_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

hf.token=${HF_TOKEN}
groq.api.key=${GROQ_API_KEY}


# Retrieval configuration
retrieval.similarity.threshold=0.7
retrieval.initial.limit=10
retrieval.final.limit=3